### ISSUE TITLE
Can't understand the procedure

### ISSUE THREAD

**Issue by nirmals-workspace** [perjo927/gitbot#1]
Hello buddy, I have gone through your Medium Post regarding this gitbot. But I can't get what exactly the procedure is. If you could elaborate a bit more by modifying your readme it would be of great help for many including me...

Also is it necessary to have a config file?

**Comment by perjo927** [comment]
Hi @Nirmal-Data-Scientist ! Thanks for contacting me. It's been 5 years since I created this repo, so unfortunately I can't recall all the required steps. Apologies!

**Comment by nirmals-workspace** [comment]
Thanks for prompt response though @perjo927 .... Have a nice day.... I will try it out on my own.... BTW this is a cool little project which would come so handy.... Thanks for making it....

**Comment by perjo927** [comment]
Glad you found it @Nirmal-Data-Scientist , if you find what's missing please feel free to open a PR!

**Comment by nirmals-workspace** [comment]
Will try and do for sure @perjo927 ....Thanks and Bye.... Have a good day if it's a day there right now😅❤️😊

**Comment by perjo927** [comment]
> Will try and do for sure @perjo927 ....Thanks and Bye.... Have a good day if it's a day there right now😅❤️😊

It sure is :) Same to you!
